# Generated by Django 3.2.4 on 2021-06-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dateTime',
            new_name='date_time',
        ),
    ]
